### ISSUE TITLE
The Perpetually Late One seems to have few commits

### ISSUE THREAD

**Issue by tofr** [gracecuenca/Chef#2]
???

**Comment by JasperCheung** [comment]
The work that he does on the project has not directly translated into commits to the repo. He mostly works with his group in class promoting discussion, asking insightful questions, and proofreading code.
He recognizes he has been slacking and will work on trying to commit more.

**Comment by tofr** [comment]
Duly noted.

Topher Brown Mykolyk
CS - Stuyvesant HS
+
